from ubuntu:14.04

maintainer Subrata Mondal <subratamondal11@gmail.com>

RUN apt-get update && apt-get install -y openssh-server && apt-get install -y apache2
RUN mkdir /var/run/sshd

# provide password o plain text
RUN echo 'root:1234' | chpasswd

# Permit root to login via ssh
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

COPY timecounter.sh /usr/local/bin/timecounter.sh
RUN chmod +x /usr/local/bin/timecounter.sh

EXPOSE 22 80
CMD ["/usr/local/bin/timecounter.sh"]
